[build-system]
requires = ["setuptools", "meson-python", "pybind11[global]", "cmake"] # cmake for asmjit
build-backend = "mesonpy"

[project]
name = "ncarray"
description="NumPy compatible non-contiguous arrays."
requires-python = ">=3.8"
dynamic = ["version"]
authors = [
    { name = "Gabriel Dorlhiac", email = "gabriel@dorlhiac.com" },
]
readme = "README.md"
urls = { Changelog = "https://github.com/XFELPP/ncarray/blob/main/CHANGELOG.md" }
classifiers = [
    "Development Status :: 3 - Alpha",
    "Environment :: GPU",
    "Environment :: GPU :: NVIDIA CUDA",
    "Environment :: GPU :: NVIDIA CUDA :: 12",
    "Intended Audience :: Developers",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: Mozilla Public License 2.0 (MPL 2.0)",
    "Operating System :: POSIX :: Linux",
    "Operating System :: Microsoft :: Windows",
    "Operating System :: MacOS",
    "Natural Language :: English",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Programming Language :: Python :: 3.14",
    "Programming Language :: C++",
    "Topic :: Scientific/Engineering",
    "Topic :: Software Development :: Libraries",
    "Topic :: Software Development :: Libraries :: Python Modules",
]

[project.scripts]
nca-pkg-config = "ncarray:nca_pkg_config"

[tool.meson-python.args]
install = ['--skip-subprojects']
